### ISSUE TITLE
LICENSE file is not part of published npm module

### ISSUE THREAD

**Issue by Parcley** [LinusU/buffer-from#5]
Sorry for annoying you with the LICENSE topic again

installing buffer-from@1.1.0
`npm install buffer-from@1.1.0`

and checking the retrieved files
`ls node_modules/buffer-from`

turns out, that the LICENSE file is not part of the distributed module. 
Only these files are present:
`index.js  package.json  readme.md`

I think it would be a good thing to include the LICENSE file with the distributed module

**Comment by char0n** [comment]
The license must be included in the distributes npm package.json, it's implicitly implied by the MIT license. If it's not included we cannot and should not use it.

**Comment by LinusU** [comment]
Sure, fixed in `1.1.1` 👌
