### ISSUE TITLE
Get error "TypeError: utf8 is not a function"

### ISSUE THREAD

**Issue by zjffun** [LinusU/buffer-from#6]
Triggering condition:
When `Buffer.alloc` and the `Buffer.allocUnsafe` function are polyfilled by other modules, and the version of node is less than v4.5.0.

Cause:
The `Buffer.from` method isn't realized until v4.5.0, but it is a function befor v4.5.0.

I think you maybe already know this and use two methods ,`Buffer.alloc` and `Buffer.allocUnsafe`, also added in v4.5.0 as auxiliary conditions to judge if the environment is modern.
Is it better to judge the version of node or try the `from` method to judge if it is really usable?

**Comment by 1010543618** [comment]
Reproduction:
Run the code below in node v4.4.7
```
var cfb = require('cfb');
var bf = require('buffer-from');
console.log(bf('test'));
```

![图片](https://user-images.githubusercontent.com/25266120/56083030-6b2dbe80-5e52-11e9-84e9-4f661aef7e9f.png)

**Comment by LinusU** [comment]
This only happens when loading the `cfb` library before, which can only lead me to believe that they are modifying something global within the buffer 🤔

**Comment by LinusU** [comment]
#7 should fix this...

**Comment by zjffun** [comment]
@LinusU 

I tried this fix, it works fine in this case.
